name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        - name: Install
          uses: borales/actions-yarn@v2.0.0
          with:
            cmd: install
        - name: Build
          run: |
            yarn run build
        - name: Deploy to Firebase
          if: success()
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting
          env:
            GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
